-ifdef(debug).
-define(idbg(FmtStr, Err), error_logger:info_msg("~p (line ~p, pid ~p): " FmtStr "~n", [?MODULE, ?LINE, self() | Err])).
-define(rdbg(Term), error_logger:info_report(Term)).
-else.
-define(idbg(_FmtStr, _Err), void).
-define(rdbg(_Term), void).
-endif.
